from dataclasses import dataclass, field
from typing import Any

from stock_data.fetcher.lixinger.risk_registry import LIXINGER_RISK_ENDPOINT_SPECS


@dataclass(frozen=True)
class EndpointMeta:
    """理杏仁接口元数据描述。"""

    api_name: str
    description: str
    market: str = "CN"
    group: str = "market_data"
    primary_keys: list[str] = field(default_factory=list)
    nullable_primary_keys: list[str] = field(default_factory=list)
    rate_limit_per_min: int = 30
    update_time: str = "18:00"
    update_delay_days: int = 0
    default_metrics: list[str] = field(default_factory=list)
    default_params: dict[str, Any] = field(default_factory=dict)
    code_param_name: str = "stockCodes"
    support_batch_prefetch: bool = False
    date_columns: list[str] = field(default_factory=list)
    required_columns: list[str] = field(default_factory=list)
    max_range_days: int | None = 3650
    pagination_required: bool = False
    frequency: str = "daily"


# 常用理杏仁 API 接口元数据注册表 (全局统一由 LixingerClient / data.yaml 控制限频)
LIXINGER_API_REGISTRY: dict[str, EndpointMeta] = {
    "cn/company/fundamental/non_financial": EndpointMeta(
        api_name="cn/company/fundamental/non_financial",
        description="A 股非金融公司基本面估值数据",
        group="fundamental",
        primary_keys=["stockCode", "date"],
        date_columns=["date"],
        required_columns=["stockCode", "date"],
        update_time="18:00",
        update_delay_days=0,
        code_param_name="stockCodes",
        default_metrics=["pe_ttm", "pb", "ps_ttm", "dyr", "mc"],
        support_batch_prefetch=True,
    ),
    "cn/company/candlestick": EndpointMeta(
        api_name="cn/company/candlestick",
        description="A 股公司 K 线行情数据",
        group="market_data",
        primary_keys=["stockCode", "date"],
        date_columns=["date"],
        required_columns=["stockCode", "date"],
        update_time="17:00",
        update_delay_days=0,
        code_param_name="stockCode",
        default_params={"type": "ex_rights"},
    ),
    "cn/index/fundamental": EndpointMeta(
        api_name="cn/index/fundamental",
        description="A 股指数基本面估值数据",
        group="fundamental",
        primary_keys=["stockCode", "date"],
        date_columns=["date"],
        required_columns=["stockCode", "date"],
        update_time="18:00",
        update_delay_days=0,
        code_param_name="stockCodes",
        default_metrics=[
            "pe_ttm.ew",
            "pe_ttm.mcw",
            "pb.ew",
            "pb.mcw",
            "ps_ttm.ew",
            "ps_ttm.mcw",
            "dyr.ew",
            "dyr.mcw",
            "mc",
        ],
    ),
    "cn/index/candlestick": EndpointMeta(
        api_name="cn/index/candlestick",
        description="A 股指数 K 线行情数据",
        group="market_data",
        primary_keys=["stockCode", "date"],
        date_columns=["date"],
        required_columns=["stockCode", "date"],
        update_time="17:00",
        update_delay_days=0,
        code_param_name="stockCode",
        default_params={"type": "normal"},
    ),
    "cn/industry/fundamental/sw_2021": EndpointMeta(
        api_name="cn/industry/fundamental/sw_2021",
        description="申万 2021 版一级行业基本面估值数据",
        group="fundamental",
        primary_keys=["stockCode", "date"],
        date_columns=["date"],
        required_columns=["stockCode", "date"],
        update_time="18:00",
        update_delay_days=0,
        code_param_name="stockCodes",
        default_metrics=["pe_ttm.ew", "pb.ew", "ps_ttm.ew", "dyr.ew", "mc"],
    ),
    "cn/industry/constituents/sw_2021": EndpointMeta(
        api_name="cn/industry/constituents/sw_2021",
        description="申万 2021 版行业成分股列表",
        group="basic_info",
        primary_keys=["industryCode", "stockCode"],
        required_columns=["industryCode", "stockCode", "market"],
        update_time="18:00",
        update_delay_days=0,
        code_param_name="stockCodes",
    ),
    "cn/company/fs/non_financial": EndpointMeta(
        api_name="cn/company/fs/non_financial",
        description="A 股非金融公司财务报表 (含商誉、经营现金流、净资产与审计意见)",
        group="financial_statement",
        primary_keys=["stockCode", "date"],
        update_time="18:00",
        update_delay_days=0,
        code_param_name="stockCodes",
        default_metrics=[
            "goodwill",
            "operating_cash_flow",
            "equity",
            "audit_opinion",
            "interest_bearing_debt",
        ],
        support_batch_prefetch=True,
    ),
    "cn/company/hot/ple": EndpointMeta(
        api_name="cn/company/hot/ple",
        description="A 股公司股权质押汇总 (含大股东质押率与全公司质押率)",
        group="risk_control",
        primary_keys=["stockCode"],
        date_columns=["last_data_date"],
        required_columns=["stockCode", "last_data_date"],
        update_time="18:00",
        update_delay_days=0,
        code_param_name="stockCodes",
        default_metrics=["ps", "ps_mc", "ps_shbt10sh_r", "ps_sc_r", "pc"],
        support_batch_prefetch=True,
    ),
    "macro/national-debt": EndpointMeta(
        api_name="macro/national-debt",
        description="国债收益率数据 (含中美国债 3M 至 30Y 期限结构)",
        group="macro_data",
        primary_keys=["areaCode", "date"],
        date_columns=["date"],
        required_columns=["areaCode", "date"],
        update_time="18:00",
        default_metrics=["tcm_y10", "tcm_y1", "tcm_y2", "tcm_y5", "tcm_y30"],
        default_params={"areaCode": "cn"},
    ),
    "macro/interest-rates": EndpointMeta(
        api_name="macro/interest-rates",
        description="宏观利率数据 (含 Shibor/同业存单/MLF/LPR/回购定盘利率)",
        group="macro_data",
        primary_keys=["areaCode", "date"],
        date_columns=["date"],
        required_columns=["areaCode", "date"],
        update_time="18:00",
        default_metrics=[
            "shibor_on",
            "shibor_w1",
            "shibor_y1",
            "cdnaaa_y1",
            "lpr_y1",
            "lpr_y5",
            "fdr_d7",
        ],
        default_params={"areaCode": "cn"},
    ),
    "macro/non-ferrous-metals": EndpointMeta(
        api_name="macro/non-ferrous-metals",
        description="全球有色金属现货价格数据 (伦敦铜/铝/锌/铅/镍/锡)",
        group="macro_data",
        primary_keys=["date"],
        date_columns=["date"],
        required_columns=["date"],
        update_time="18:00",
        default_metrics=["l_cu_p", "l_zn_p", "l_pb_p", "l_al_p", "l_ni_p", "l_sn_p"],
        default_params={"areaCode": "us"},
    ),
    "macro/crude-oil": EndpointMeta(
        api_name="macro/crude-oil",
        description="国际原油现货价格数据 (WTI 与布伦特原油)",
        group="macro_data",
        primary_keys=["date"],
        date_columns=["date"],
        required_columns=["date"],
        update_time="18:00",
        default_metrics=["wti_co_sp", "brent_co_sp"],
        default_params={"areaCode": "us"},
    ),
    "macro/investor": EndpointMeta(
        api_name="macro/investor",
        description="A 股投资者存量与新增账户数据",
        frequency="monthly",
        group="macro_data",
        primary_keys=["date"],
        date_columns=["date"],
        required_columns=["date"],
        update_time="18:00",
        default_metrics=["ni", "non_ni", "nni_m", "n_non_ni_m"],
        default_params={"areaCode": "cn"},
        max_range_days=3650,
    ),
    "macro/money-supply": EndpointMeta(
        api_name="macro/money-supply",
        description="大陆 M0/M1/M2 月度货币供应量",
        frequency="monthly",
        group="macro_data",
        primary_keys=["month"],
        date_columns=["month"],
        required_columns=["month"],
        update_time="18:00",
        default_metrics=[
            "m.m0.t",
            "m.m0.t_y2y",
            "m.m1.t",
            "m.m1.t_y2y",
            "m.m2.t",
            "m.m2.t_y2y",
        ],
        default_params={"areaCode": "cn"},
        max_range_days=3650,
    ),
    "macro/social-financing": EndpointMeta(
        api_name="macro/social-financing",
        description="大陆社会融资规模存量及同比",
        frequency="monthly",
        group="macro_data",
        primary_keys=["month"],
        date_columns=["month"],
        required_columns=["month"],
        update_time="18:00",
        default_metrics=["m.sf.t", "m.sf.t_y2y"],
        default_params={"areaCode": "cn"},
        max_range_days=3650,
    ),
    "cn/industry/fs/sw_2021/non_financial": EndpointMeta(
        api_name="cn/industry/fs/sw_2021/non_financial",
        description="申万 2021 版非金融行业财务报表数据 (含营收/净利/毛利/ROE等多维指标)",
        group="financial_statement",
        primary_keys=["stockCode", "date"],
        date_columns=["date"],
        required_columns=["stockCode", "date"],
        update_time="18:00",
        update_delay_days=0,
        code_param_name="stockCodes",
        default_metrics=[
            "q.ps.toi.c_y2y",
            "q.ps.np.c_y2y",
            "q.ps.gp_m.ttm",
            "q.m.roe.ttm",
            "q.ps.toi.ttm_y2y",
            "q.ps.np.ttm_y2y",
        ],
        support_batch_prefetch=True,
    ),
    "cn/industry/fs/sw_2021/bank": EndpointMeta(
        api_name="cn/industry/fs/sw_2021/bank",
        description="申万 2021 版银行行业财务报表数据 (含净利息收入/非息收入/成本收入比/ROE)",
        group="financial_statement",
        primary_keys=["stockCode", "date"],
        date_columns=["date"],
        required_columns=["stockCode", "date"],
        update_time="18:00",
        update_delay_days=0,
        code_param_name="stockCodes",
        default_metrics=[
            "q.ps.toi.c_y2y",
            "q.ps.np.c_y2y",
            "q.m.roe.ttm",
            "q.ps.toi.ttm_y2y",
            "q.ps.np.ttm_y2y",
        ],
        support_batch_prefetch=True,
    ),
    "cn/industry/fs/sw_2021/security": EndpointMeta(
        api_name="cn/industry/fs/sw_2021/security",
        description="申万 2021 版证券行业财务报表数据 (含经纪/投行/资管净收入与自营投资收益)",
        group="financial_statement",
        primary_keys=["stockCode", "date"],
        date_columns=["date"],
        required_columns=["stockCode", "date"],
        update_time="18:00",
        update_delay_days=0,
        code_param_name="stockCodes",
        default_metrics=[
            "q.ps.toi.c_y2y",
            "q.ps.np.c_y2y",
            "q.m.roe.ttm",
            "q.ps.toi.ttm_y2y",
            "q.ps.np.ttm_y2y",
        ],
        support_batch_prefetch=True,
    ),
    "cn/industry/fs/sw_2021/insurance": EndpointMeta(
        api_name="cn/industry/fs/sw_2021/insurance",
        description="申万 2021 版保险行业财务报表数据 (含已赚保费/内含价值/新业务价值/营运利润)",
        group="financial_statement",
        primary_keys=["stockCode", "date"],
        date_columns=["date"],
        required_columns=["stockCode", "date"],
        update_time="18:00",
        update_delay_days=0,
        code_param_name="stockCodes",
        default_metrics=[
            "q.ps.toi.c_y2y",
            "q.ps.np.c_y2y",
            "q.m.roe.ttm",
            "q.ps.toi.ttm_y2y",
            "q.ps.np.ttm_y2y",
        ],
        support_batch_prefetch=True,
    ),
    "cn/company/fs/non_financial": EndpointMeta(
        api_name="cn/company/fs/non_financial",
        description="A 股非金融公司财务报表 (含商誉、经营现金流、净资产与审计意见)",
        group="financial_statement",
        primary_keys=["stockCode", "date"],
        update_time="18:00",
        update_delay_days=0,
        code_param_name="stockCodes",
        default_metrics=["q.ps.toi.t", "q.ps.np.t", "q.bs.gw.t", "q.cfs.ncffoa.t"],
        support_batch_prefetch=True,
    ),
    "cn/company/fs/bank": EndpointMeta(
        api_name="cn/company/fs/bank",
        description="A 股银行公司财务报表 (含净息差、不良率、拨备覆盖率、资本充足率)",
        group="financial_statement",
        primary_keys=["stockCode", "date"],
        update_time="18:00",
        update_delay_days=0,
        code_param_name="stockCodes",
        default_metrics=[
            "q.ps.toi.t",
            "q.ps.np.t",
            "q.bs.nim.t",
            "q.bs.npl.t",
        ],
        support_batch_prefetch=True,
    ),
    "cn/company/fs/security": EndpointMeta(
        api_name="cn/company/fs/security",
        description="A 股证券公司财务报表 (含净资本、经纪/投行/自营业务净收入)",
        group="financial_statement",
        primary_keys=["stockCode", "date"],
        update_time="18:00",
        update_delay_days=0,
        code_param_name="stockCodes",
        default_metrics=["q.ps.toi.t", "q.ps.np.t"],
        support_batch_prefetch=True,
    ),
    "cn/company/fs/insurance": EndpointMeta(
        api_name="cn/company/fs/insurance",
        description="A 股保险公司财务报表 (含内含价值 EV、新业务价值 NBV、已赚保费)",
        group="financial_statement",
        primary_keys=["stockCode", "date"],
        update_time="18:00",
        update_delay_days=0,
        code_param_name="stockCodes",
        default_metrics=["q.ps.toi.t", "q.ps.np.t", "q.ps.ep.t"],
        support_batch_prefetch=True,
    ),
}

for _api_name, _spec in LIXINGER_RISK_ENDPOINT_SPECS.items():
    LIXINGER_API_REGISTRY[_api_name] = EndpointMeta(api_name=_api_name, **_spec)

for _meta in {id(meta): meta for meta in LIXINGER_API_REGISTRY.values()}.values():
    if not _meta.required_columns:
        _meta.required_columns.extend(_meta.primary_keys)
    if not _meta.date_columns:
        _meta.date_columns.extend(key for key in _meta.primary_keys if key in {"date", "endDate"})
