"""TuShare 财务、宏观与资金流接口注册表。"""

from stock_data.fetcher.tushare.registry_meta import EndpointMeta

FINANCE_ENDPOINTS: dict[str, EndpointMeta] = {
    "stk_holdertrade": EndpointMeta(
        api_name="stk_holdertrade",
        description="上市公司股东及董监高增减持事件",
        frequency="event",
        query_mode="ann_date",
        group="corporate_action",
        primary_keys=["ts_code", "ann_date", "holder_name", "in_de", "change_vol"],
        date_columns=["ann_date", "begin_date", "close_date"],
        required_columns=["ts_code", "ann_date", "holder_name", "in_de", "change_vol"],
        units={
            "change_vol": "share",
            "change_ratio": "percent",
            "after_share": "share",
            "after_ratio": "percent",
            "avg_price": "CNY/share",
            "total_share": "share",
        },
        request_window_days=31,
        max_rows_per_request=3000,
        request_fields=(
            "ts_code,ann_date,holder_name,holder_type,in_de,change_vol,change_ratio,"
            "after_share,after_ratio,avg_price,total_share,begin_date,close_date"
        ),
    ),
    "repurchase": EndpointMeta(
        api_name="repurchase",
        description="上市公司股票回购计划与实施事件",
        frequency="event",
        query_mode="ann_date",
        group="corporate_action",
        primary_keys=["ts_code", "ann_date", "proc"],
        date_columns=["ann_date", "end_date", "exp_date"],
        required_columns=["ts_code", "ann_date", "proc"],
        units={
            "vol": "share",
            "amount": "CNY",
            "high_limit": "CNY/share",
            "low_limit": "CNY/share",
        },
        request_window_days=31,
        max_rows_per_request=2000,
        request_fields=("ts_code,ann_date,end_date,proc,exp_date,vol,amount,high_limit,low_limit"),
    ),
    "block_trade": EndpointMeta(
        api_name="block_trade",
        description="股票大宗交易明细",
        frequency="event",
        query_mode="trade_date",
        group="corporate_action",
        primary_keys=["ts_code", "trade_date", "price", "vol", "buyer", "seller"],
        nullable_primary_keys=["buyer", "seller"],
        date_columns=["trade_date"],
        required_columns=["ts_code", "trade_date", "price", "vol", "amount"],
        units={
            "price": "CNY/share",
            "vol": "10k_share",
            "amount": "CNY10k",
        },
        request_window_days=31,
        max_rows_per_request=1000,
        request_fields="ts_code,trade_date,price,vol,amount,buyer,seller",
    ),
    "share_float": EndpointMeta(
        api_name="share_float",
        description="限售股解禁明细",
        frequency="event",
        query_mode="float_date",
        group="corporate_action",
        primary_keys=["ts_code", "ann_date", "float_date", "holder_name", "share_type"],
        date_columns=["float_date", "ann_date"],
        required_columns=["ts_code", "ann_date", "float_date", "float_share", "float_ratio"],
        units={
            "float_share": "share",
            "float_ratio": "percent",
        },
        request_window_days=30,
        max_rows_per_request=6000,
        request_fields=(
            "ts_code,ann_date,float_date,float_share,float_ratio,holder_name,share_type"
        ),
    ),
    "pledge_detail": EndpointMeta(
        api_name="pledge_detail",
        description="股票股权质押逐笔明细",
        frequency="event",
        query_mode="ann_date",
        group="corporate_action",
        primary_keys=["ts_code", "ann_date", "holder_name", "start_date"],
        date_columns=["ann_date", "start_date", "end_date", "release_date"],
        required_columns=["ts_code", "ann_date", "holder_name", "pledge_amount"],
        units={
            "pledge_amount": "10k_share",
            "holding_amount": "10k_share",
            "pledged_amount": "10k_share",
            "p_total_ratio": "percent",
            "h_total_ratio": "percent",
        },
        request_window_days=365,
        max_rows_per_request=1000,
        request_fields=(
            "ts_code,ann_date,holder_name,pledge_amount,start_date,end_date,is_release,"
            "release_date,pledgor,holding_amount,pledged_amount,p_total_ratio,h_total_ratio,is_buyback"
        ),
    ),
    "pledge_stat": EndpointMeta(
        api_name="pledge_stat",
        description="股票股权质押统计",
        frequency="event",
        query_mode="end_date",
        group="market_indicators",
        primary_keys=["ts_code", "end_date"],
        date_columns=["end_date"],
        required_columns=["ts_code", "end_date", "pledge_ratio"],
        units={
            "unrest_pledge": "10k_share",
            "rest_pledge": "10k_share",
            "total_share": "share",
            "pledge_ratio": "percent",
        },
        request_window_days=365,
        max_rows_per_request=1000,
        request_fields=(
            "ts_code,end_date,pledge_count,unrest_pledge,rest_pledge,total_share,pledge_ratio"
        ),
    ),
    "income": EndpointMeta(
        api_name="income_vip",
        description="上市公司利润表",
        frequency="quarterly",
        query_mode="period",
        group="financial_statements",
        primary_keys=["ts_code", "end_date"],
        date_columns=["end_date"],
        required_columns=["ts_code", "end_date"],
    ),
    "fina_indicator": EndpointMeta(
        api_name="fina_indicator_vip",
        description="财务指标数据（ROE/毛利率等）",
        frequency="quarterly",
        query_mode="period",
        group="financial_statements",
        primary_keys=["ts_code", "end_date"],
        date_columns=["end_date"],
        required_columns=["ts_code", "end_date"],
    ),
    "moneyflow": EndpointMeta(
        api_name="moneyflow",
        description="个股资金流向",
        frequency="daily",
        group="money_flow",
        primary_keys=["ts_code", "trade_date"],
    ),
    "hk_hold": EndpointMeta(
        api_name="hk_hold",
        description="沪深港通持股明细（北向资金）",
        frequency="daily",
        group="money_flow",
        primary_keys=["ts_code", "trade_date"],
        date_columns=["trade_date"],
        required_columns=["ts_code", "trade_date"],
        update_time="08:00",
        update_delay_days=1,
        delay_in_trading_days=True,
        request_window_days=1,
    ),
    "margin": EndpointMeta(
        api_name="margin",
        description="融资融券交易汇总",
        frequency="daily",
        group="market_indicators",
        primary_keys=["trade_date", "exchange_id"],
        update_time="08:00",
        update_delay_days=1,
        delay_in_trading_days=True,
        request_window_days=90,
    ),
    "margin_detail": EndpointMeta(
        api_name="margin_detail",
        description="融资融券交易明细",
        frequency="daily",
        group="market_data",
        primary_keys=["ts_code", "trade_date"],
        date_columns=["trade_date"],
        required_columns=["ts_code", "trade_date"],
        update_time="08:00",
        update_delay_days=1,
        delay_in_trading_days=True,
        request_window_days=365,
        max_rows_per_request=6000,
    ),
    "moneyflow_hsgt": EndpointMeta(
        api_name="moneyflow_hsgt",
        description="沪深港通资金流向",
        frequency="daily",
        group="money_flow",
        primary_keys=["trade_date"],
        update_time="20:00",
    ),
    "hsgt_top10": EndpointMeta(
        api_name="hsgt_top10",
        description="沪深港通十大成交股",
        frequency="daily",
        group="money_flow",
        primary_keys=["trade_date", "ts_code", "market_type"],
        date_columns=["trade_date"],
        required_columns=["ts_code", "trade_date", "market_type"],
        update_time="20:00",
        request_window_days=30,
    ),
    "cn_gdp": EndpointMeta(
        api_name="cn_gdp",
        description="国内生产总值 GDP",
        frequency="quarterly",
        group="macro_data",
        primary_keys=["quarter"],
        query_mode="quarter",
    ),
    "cn_cpi": EndpointMeta(
        api_name="cn_cpi",
        description="居民消费价格指数 CPI",
        frequency="monthly",
        group="macro_data",
        primary_keys=["month"],
        query_mode="month",
    ),
    "cn_ppi": EndpointMeta(
        api_name="cn_ppi",
        description="工业生产者出厂价格指数 PPI",
        frequency="monthly",
        group="macro_data",
        primary_keys=["month"],
        query_mode="month",
    ),
    "cn_pmi": EndpointMeta(
        api_name="cn_pmi",
        description="采购经理人指数 PMI",
        frequency="monthly",
        group="macro_data",
        primary_keys=["month"],
        query_mode="month",
    ),
    "cn_m": EndpointMeta(
        api_name="cn_m",
        description="货币供应量 M0/M1/M2",
        frequency="monthly",
        group="macro_data",
        primary_keys=["month"],
        query_mode="month",
    ),
    "sf_month": EndpointMeta(
        api_name="sf_month",
        description="社会融资规模",
        frequency="monthly",
        group="macro_data",
        primary_keys=["month"],
        query_mode="month",
    ),
    "shibor": EndpointMeta(
        api_name="shibor",
        description="Shibor 银行间同业拆放利率",
        frequency="daily",
        group="macro_data",
        primary_keys=["date"],
        query_mode="date",
        date_columns=["date"],
        required_columns=["date"],
    ),
    "shibor_lpr": EndpointMeta(
        api_name="shibor_lpr",
        description="LPR 贷款基础利率",
        frequency="monthly",
        group="macro_data",
        primary_keys=["date"],
        query_mode="date",
        date_columns=["date"],
        required_columns=["date"],
    ),
    "cn_schedule": EndpointMeta(
        api_name="cn_schedule",
        description="中国经济数据发布日程",
        frequency="monthly",
        group="macro_data",
        primary_keys=["publish_date", "title"],
        query_mode="month",
        date_columns=["month", "publish_date"],
        required_columns=["publish_date", "title"],
    ),
    "forecast": EndpointMeta(
        api_name="forecast",
        description="上市公司业绩预告 (PIT)",
        frequency="quarterly",
        group="financial_statements",
        primary_keys=["ts_code", "ann_date", "end_date"],
        date_columns=["ann_date", "end_date"],
        required_columns=["ts_code", "ann_date", "end_date"],
    ),
    "express": EndpointMeta(
        api_name="express",
        description="上市公司业绩快报 (PIT)",
        frequency="quarterly",
        group="financial_statements",
        primary_keys=["ts_code", "ann_date", "end_date"],
        date_columns=["ann_date", "end_date"],
        required_columns=["ts_code", "ann_date", "end_date"],
    ),
    "balancesheet": EndpointMeta(
        api_name="balancesheet_vip",
        description="上市公司资产负债表 (PIT)",
        frequency="quarterly",
        query_mode="period",
        group="financial_statements",
        primary_keys=["ts_code", "ann_date", "end_date"],
        date_columns=["end_date", "ann_date"],
        required_columns=["ts_code", "ann_date", "end_date"],
    ),
    "cashflow": EndpointMeta(
        api_name="cashflow_vip",
        description="上市公司现金流量表 (PIT)",
        frequency="quarterly",
        query_mode="period",
        group="financial_statements",
        primary_keys=["ts_code", "ann_date", "end_date"],
        date_columns=["end_date", "ann_date"],
        required_columns=["ts_code", "ann_date", "end_date"],
    ),
    "report_rc": EndpointMeta(
        api_name="report_rc",
        description="卖方机构盈利预测数据 (分析师一致预期)",
        frequency="daily",
        group="financial_statements",
        primary_keys=["ts_code", "report_date", "org_name", "quarter"],
        date_columns=["report_date"],
        required_columns=["ts_code", "report_date", "org_name"],
    ),
    "stk_account": EndpointMeta(
        api_name="stk_account",
        description="股票账户开户数据（官方已停止更新）",
        frequency="weekly",
        group="macro_data",
        primary_keys=["date"],
        date_columns=["date"],
        required_columns=["date"],
        update_delay_days=1,
    ),
}


# 财务报表公开任务统一路由到 VIP 全市场接口；保留 API 名称别名供内部元数据查找。
_VIP_FINANCIAL_STATEMENT_APIS = {
    "income": "income_vip",
    "fina_indicator": "fina_indicator_vip",
    "balancesheet": "balancesheet_vip",
    "cashflow": "cashflow_vip",
}

for _public_name, _vip_api_name in _VIP_FINANCIAL_STATEMENT_APIS.items():
    FINANCE_ENDPOINTS[_vip_api_name] = FINANCE_ENDPOINTS[_public_name]
