"""TuShare 基础信息与行情类接口注册表。"""

from stock_data.fetcher.tushare.registry_meta import EndpointMeta

MARKET_ENDPOINTS: dict[str, EndpointMeta] = {
    "daily": EndpointMeta(
        api_name="daily",
        description="A 股日线行情",
        frequency="daily",
        group="market_data",
        primary_keys=["ts_code", "trade_date"],
        update_time="17:00",
        update_delay_days=0,
        date_columns=["trade_date"],
        required_columns=["ts_code", "trade_date", "open", "high", "low", "close"],
    ),
    "daily_basic": EndpointMeta(
        api_name="daily_basic",
        description="每日指标（换手率、PE、PB、总市值等）",
        frequency="daily",
        group="market_indicators",
        primary_keys=["ts_code", "trade_date"],
        update_time="18:00",
        update_delay_days=0,
        date_columns=["trade_date"],
        required_columns=["ts_code", "trade_date"],
        max_rows_per_request=6000,
    ),
    "stk_limit": EndpointMeta(
        api_name="stk_limit",
        description="每日涨跌停价格",
        frequency="daily",
        group="market_data",
        primary_keys=["ts_code", "trade_date"],
        update_time="08:40",
        update_delay_days=0,
        date_columns=["trade_date"],
        required_columns=["ts_code", "trade_date", "up_limit", "down_limit"],
        request_window_days=1,
        max_rows_per_request=5800,
    ),
    "limit_list_d": EndpointMeta(
        api_name="limit_list_d",
        description="每日涨跌停与炸板事件",
        frequency="daily",
        group="market_data",
        primary_keys=["ts_code", "trade_date", "limit"],
        date_columns=["trade_date"],
        required_columns=["ts_code", "trade_date", "limit"],
        request_window_days=1,
        max_rows_per_request=2500,
    ),
    "stock_basic": EndpointMeta(
        api_name="stock_basic",
        description="基础股票列表",
        frequency="event",
        group="basic_info",
        primary_keys=["ts_code"],
        required_columns=["ts_code"],
        pagination_required=True,
    ),
    "adj_factor": EndpointMeta(
        api_name="adj_factor",
        description="复权因子数据",
        frequency="daily",
        group="market_data",
        primary_keys=["ts_code", "trade_date"],
        date_columns=["trade_date"],
        required_columns=["ts_code", "trade_date"],
    ),
    "index_daily": EndpointMeta(
        api_name="index_daily",
        description="指数日线行情",
        frequency="daily",
        group="market_data",
        primary_keys=["ts_code", "trade_date"],
        date_columns=["trade_date"],
        required_columns=["ts_code", "trade_date", "open", "high", "low", "close"],
        max_rows_per_request=8000,
    ),
    "suspend_d": EndpointMeta(
        api_name="suspend_d",
        description="每日停复牌信息",
        frequency="daily",
        group="market_data",
        primary_keys=["ts_code", "trade_date"],
        date_columns=["trade_date"],
        required_columns=["ts_code", "trade_date"],
    ),
    "index_basic": EndpointMeta(
        api_name="index_basic",
        description="指数基本信息",
        frequency="event",
        group="basic_info",
        primary_keys=["ts_code"],
    ),
    "index_dailybasic": EndpointMeta(
        api_name="index_dailybasic",
        description="指数每日估值与指标",
        frequency="daily",
        group="market_indicators",
        primary_keys=["ts_code", "trade_date"],
    ),
    "index_weight": EndpointMeta(
        api_name="index_weight",
        description="指数成分股权重",
        frequency="monthly",
        group="basic_info",
        primary_keys=["index_code", "con_code", "trade_date"],
    ),
    "index_classify": EndpointMeta(
        api_name="index_classify",
        description="申万行业分类",
        frequency="event",
        group="basic_info",
        primary_keys=["index_code", "src"],
    ),
    "index_member": EndpointMeta(
        api_name="index_member",
        description="申万行业成分股",
        frequency="event",
        group="basic_info",
        primary_keys=["index_code", "con_code", "in_date", "out_date"],
        required_columns=["index_code", "con_code", "in_date", "out_date"],
    ),
    "sw_daily": EndpointMeta(
        api_name="sw_daily",
        description="申万行业日线行情",
        frequency="daily",
        group="market_data",
        primary_keys=["ts_code", "trade_date"],
    ),
    "fund_basic": EndpointMeta(
        api_name="fund_basic",
        description="基金基本信息",
        frequency="static",
        group="basic_info",
        primary_keys=["ts_code"],
    ),
    "fund_daily": EndpointMeta(
        api_name="fund_daily",
        description="基金日线行情",
        group="market_data",
        primary_keys=["ts_code", "trade_date"],
    ),
    "fund_adj": EndpointMeta(
        api_name="fund_adj",
        description="场内基金复权因子",
        group="market_data",
        primary_keys=["ts_code", "trade_date"],
    ),
    "fund_share": EndpointMeta(
        api_name="fund_share",
        description="基金份额规模",
        group="market_indicators",
        primary_keys=["ts_code", "trade_date"],
        date_columns=["trade_date"],
        required_columns=["ts_code", "trade_date"],
    ),
    "etf_share_size": EndpointMeta(
        api_name="etf_share_size",
        description="ETF 基金份额与资产规模",
        group="market_indicators",
        primary_keys=["ts_code", "trade_date"],
    ),
    "fut_index_daily": EndpointMeta(
        api_name="fut_index_daily",
        description="南华期货/商品/工业品指数日线行情",
        group="market_data",
        primary_keys=["ts_code", "trade_date"],
        date_columns=["trade_date"],
        required_columns=["ts_code", "trade_date", "open", "high", "low", "close"],
    ),
    "opt_basic": EndpointMeta(
        api_name="opt_basic",
        description="期权合约基础信息（期权原始数据输入）",
        frequency="static",
        group="options",
        primary_keys=["ts_code"],
        date_columns=["list_date", "delist_date"],
        required_columns=["ts_code", "exchange", "name"],
        pagination_required=True,
    ),
    "opt_daily": EndpointMeta(
        api_name="opt_daily",
        description="期权日线行情（期权原始数据输入）",
        frequency="daily",
        group="options",
        primary_keys=["ts_code", "trade_date"],
        date_columns=["trade_date"],
        required_columns=["ts_code", "trade_date", "close", "settle"],
        request_window_days=1,
        max_rows_per_request=15000,
    ),
    "cb_basic": EndpointMeta(
        api_name="cb_basic",
        description="可转债基础信息",
        frequency="static",
        group="bond_data",
        primary_keys=["ts_code"],
        date_columns=["list_date", "delist_date"],
        required_columns=["ts_code", "bond_short_name", "stk_code", "list_date", "exchange"],
        units={
            "par": "CNY/bond",
            "issue_price": "CNY/bond",
            "issue_size": "CNY",
            "remain_size": "CNY",
            "coupon_rate": "percent",
            "add_rate": "percent",
            "first_conv_price": "CNY/share",
            "conv_price": "CNY/share",
        },
        request_fields=(
            "ts_code,bond_full_name,bond_short_name,cb_code,cb_type,stk_code,stk_short_name,"
            "maturity,par,issue_price,issue_size,remain_size,value_date,maturity_date,rate_type,"
            "coupon_rate,add_rate,pay_per_year,list_date,delist_date,exchange,conv_start_date,"
            "conv_end_date,conv_stop_date,first_conv_price,conv_price,issue_rating,newest_rating,"
            "rating_comp"
        ),
        max_rows_per_request=2000,
    ),
    "cb_daily": EndpointMeta(
        api_name="cb_daily",
        description="可转债日行情与转股溢价率",
        frequency="daily",
        group="bond_data",
        primary_keys=["ts_code", "trade_date"],
        date_columns=["trade_date"],
        required_columns=["ts_code", "trade_date", "close"],
        units={
            "pre_close": "CNY/bond",
            "open": "CNY/bond",
            "high": "CNY/bond",
            "low": "CNY/bond",
            "close": "CNY/bond",
            "change": "CNY/bond",
            "pct_chg": "percent",
            "vol": "hand",
            "amount": "CNY10k",
            "bond_value": "CNY/bond",
            "bond_over_rate": "percent",
            "cb_value": "CNY/bond",
            "cb_over_rate": "percent",
        },
        query_mode="trade_date",
        request_window_days=1,
        max_rows_per_request=2000,
        request_fields=(
            "ts_code,trade_date,pre_close,open,high,low,close,change,pct_chg,vol,amount,"
            "bond_value,bond_over_rate,cb_value,cb_over_rate"
        ),
    ),
    "trade_cal": EndpointMeta(
        api_name="trade_cal",
        description="A 股各大交易所开闭市交易日历",
        frequency="static",
        group="basic_info",
        primary_keys=["exchange", "cal_date"],
        date_columns=["cal_date"],
        required_columns=["exchange", "cal_date", "is_open"],
    ),
}
