"""市场温度计解读与配置模块。"""

from stock_reporting.interpretation.market_temperature.config import (
    DEFAULT_CONFIG_PATH,
    BandsConfig,
    MarketTemperatureConfig,
    load_market_temperature_config,
)
from stock_reporting.interpretation.market_temperature.interpretation import (
    _DIMENSION_FOCUS,
    _DIMENSION_LABELS,
    _DIMENSION_TIMELINESS,
    _METRIC_LABELS,
    evaluate_external_pressure_section,
    evaluate_follow_ups,
    evaluate_interpretation_priority_rows,
    evaluate_key_divergences,
    evaluate_one_line_summary,
    evaluate_reading_brief,
    evaluate_systemic_risk_section,
    get_cross_period_comment,
    get_dimension_comment,
    get_pressure_band,
    get_pressure_comment,
    get_systemic_risk_level,
    get_temperature_band,
)

__all__ = [
    "DEFAULT_CONFIG_PATH",
    "_DIMENSION_FOCUS",
    "_DIMENSION_LABELS",
    "_DIMENSION_TIMELINESS",
    "_METRIC_LABELS",
    "BandsConfig",
    "MarketTemperatureConfig",
    "evaluate_external_pressure_section",
    "evaluate_follow_ups",
    "evaluate_interpretation_priority_rows",
    "evaluate_key_divergences",
    "evaluate_one_line_summary",
    "evaluate_reading_brief",
    "evaluate_systemic_risk_section",
    "get_cross_period_comment",
    "get_dimension_comment",
    "get_pressure_band",
    "get_pressure_comment",
    "get_systemic_risk_level",
    "get_temperature_band",
    "load_market_temperature_config",
]
